### ISSUE TITLE
denops complains if tmux is not running

### ISSUE THREAD

**Issue by sqrtmau** [delphinus/ddc-tmux#4]
`denops` complains if tmux is not running：

```
[denops] no server running on /tmp/tmux-1000/default
```

**Comment by delphinus** [comment]
Good catch! Fixed on 1ccc0f9

**Comment by delphinus** [comment]
Reverted 1ccc0f9 and finally fixed on 5a3e900.

This is needed for the case nvim is not on the pane of `tmux` but another `tmux` instance is running on background.
